; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; REQUIRES: amdgpu-registered-target
; RUN: opt < %s -mtriple=amdgcn-amd-amdhsa -passes='require<uniformity>,nary-reassociate' -S | FileCheck %s

declare i32 @llvm.amdgcn.workitem.id.x()
declare void @use(i32)

; Test that NaryReassociate prefers grouping uniform values together when
; uniformity analysis is available and both reassociation options exist.
;
; For I = (A op B) op RHS, the pass can form:
;   - (A op RHS) op B
;   - (B op RHS) op A
;
; When both dominating expressions exist, prefer the one grouping uniforms.

; Both %d_u2 and %u1_u2 exist as dominating expressions.
; For (d + u1) + u2:
;   - Without UA preference: would try (d + u2) first, find %d_u2, return %d_u2 + u1
;   - With UA preference: B=u1 and RHS=u2 are uniform, A=d is divergent
;                         So prefer (u1 + u2) + d, returning %u1_u2 + d
;

define amdgpu_kernel void @prefer_uniform_grouping(i32 %u1, i32 %u2) {
; CHECK-LABEL: define amdgpu_kernel void @prefer_uniform_grouping(
; CHECK-SAME: i32 [[U1:%.*]], i32 [[U2:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[D_U2:%.*]] = add i32 [[D]], [[U2]]
; CHECK-NEXT:    [[U1_U2:%.*]] = add i32 [[U1]], [[U2]]
; CHECK-NEXT:    call void @use(i32 [[D_U2]])
; CHECK-NEXT:    call void @use(i32 [[U1_U2]])
; CHECK-NEXT:    [[RESULT:%.*]] = add i32 [[U1_U2]], [[D]]
; CHECK-NEXT:    call void @use(i32 [[RESULT]])
; CHECK-NEXT:    ret void
;
  %d = call i32 @llvm.amdgcn.workitem.id.x()

  ; Create both possible reassociation targets
  %d_u2 = add i32 %d, %u2        ; divergent + uniform
  %u1_u2 = add i32 %u1, %u2      ; uniform + uniform (should be preferred!)

  call void @use(i32 %d_u2)
  call void @use(i32 %u1_u2)

  ; (d + u1) + u2: both (d + u2) and (u1 + u2) exist
  ; Should prefer (u1 + u2) + d to group uniforms
  %tmp = add i32 %d, %u1
  %result = add i32 %tmp, %u2
  call void @use(i32 %result)

  ret void
}

define amdgpu_kernel void @prefer_uniform_grouping_mul(i32 %u1, i32 %u2) {
; CHECK-LABEL: define amdgpu_kernel void @prefer_uniform_grouping_mul(
; CHECK-SAME: i32 [[U1:%.*]], i32 [[U2:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[D_U2:%.*]] = mul i32 [[D]], [[U2]]
; CHECK-NEXT:    [[U1_U2:%.*]] = mul i32 [[U1]], [[U2]]
; CHECK-NEXT:    call void @use(i32 [[D_U2]])
; CHECK-NEXT:    call void @use(i32 [[U1_U2]])
; CHECK-NEXT:    [[RESULT:%.*]] = mul i32 [[U1_U2]], [[D]]
; CHECK-NEXT:    call void @use(i32 [[RESULT]])
; CHECK-NEXT:    ret void
;
  %d = call i32 @llvm.amdgcn.workitem.id.x()

  %d_u2 = mul i32 %d, %u2
  %u1_u2 = mul i32 %u1, %u2

  call void @use(i32 %d_u2)
  call void @use(i32 %u1_u2)

  %tmp = mul i32 %d, %u1
  %result = mul i32 %tmp, %u2
  call void @use(i32 %result)

  ret void
}

define amdgpu_kernel void @only_one_option(i32 %u1, i32 %u2) {
; CHECK-LABEL: define amdgpu_kernel void @only_one_option(
; CHECK-SAME: i32 [[U1:%.*]], i32 [[U2:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[U1_U2:%.*]] = add i32 [[U1]], [[U2]]
; CHECK-NEXT:    call void @use(i32 [[U1_U2]])
; CHECK-NEXT:    [[RESULT:%.*]] = add i32 [[U1_U2]], [[D]]
; CHECK-NEXT:    call void @use(i32 [[RESULT]])
; CHECK-NEXT:    ret void
;
  %d = call i32 @llvm.amdgcn.workitem.id.x()

  ; Only u1 + u2 exists, not d + u2
  %u1_u2 = add i32 %u1, %u2
  call void @use(i32 %u1_u2)

  %tmp = add i32 %d, %u1
  %result = add i32 %tmp, %u2
  call void @use(i32 %result)

  ret void
}

; When no dominating expression exists, no reassociation happens
define amdgpu_kernel void @no_dominating_expr(i32 %u1, i32 %u2) {
; CHECK-LABEL: define amdgpu_kernel void @no_dominating_expr(
; CHECK-SAME: i32 [[U1:%.*]], i32 [[U2:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[TMP:%.*]] = add i32 [[D]], [[U1]]
; CHECK-NEXT:    [[RESULT:%.*]] = add i32 [[TMP]], [[U2]]
; CHECK-NEXT:    call void @use(i32 [[RESULT]])
; CHECK-NEXT:    ret void
;
  %d = call i32 @llvm.amdgcn.workitem.id.x()

  ; No dominating expressions exist
  %tmp = add i32 %d, %u1
  %result = add i32 %tmp, %u2
  call void @use(i32 %result)

  ret void
}

; Test smax: prefer grouping uniform values together
; For smax(smax(A, B), RHS):
;   - smax(smax(A, RHS), B): groups A and RHS
;   - smax(smax(B, RHS), A): groups B and RHS
; When B and RHS are uniform but A is divergent, prefer smax(smax(B, RHS), A)
define amdgpu_kernel void @prefer_uniform_grouping_smax(i32 %u1, i32 %u2) {
; CHECK-LABEL: define amdgpu_kernel void @prefer_uniform_grouping_smax(
; CHECK-SAME: i32 [[U1:%.*]], i32 [[U2:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[D_U2:%.*]] = call i32 @llvm.smax.i32(i32 [[D]], i32 [[U2]])
; CHECK-NEXT:    [[U1_U2:%.*]] = call i32 @llvm.smax.i32(i32 [[U1]], i32 [[U2]])
; CHECK-NEXT:    call void @use(i32 [[D_U2]])
; CHECK-NEXT:    call void @use(i32 [[U1_U2]])
; CHECK-NEXT:    [[RESULT_NARY:%.*]] = call i32 @llvm.smax.i32(i32 [[U1_U2]], i32 [[D]])
; CHECK-NEXT:    call void @use(i32 [[RESULT_NARY]])
; CHECK-NEXT:    ret void
;
  %d = call i32 @llvm.amdgcn.workitem.id.x()

  ; Create both possible reassociation targets
  %d_u2 = call i32 @llvm.smax.i32(i32 %d, i32 %u2)    ; divergent, uniform
  %u1_u2 = call i32 @llvm.smax.i32(i32 %u1, i32 %u2)  ; uniform, uniform (preferred!)

  call void @use(i32 %d_u2)
  call void @use(i32 %u1_u2)

  ; smax(smax(d, u1), u2): both smax(d, u2) and smax(u1, u2) exist
  ; Should prefer smax(smax(u1, u2), d) to group uniforms
  %tmp = call i32 @llvm.smax.i32(i32 %d, i32 %u1)
  %result = call i32 @llvm.smax.i32(i32 %tmp, i32 %u2)
  call void @use(i32 %result)

  ret void
}

; Test umin: prefer grouping uniform values together
define amdgpu_kernel void @prefer_uniform_grouping_umin(i32 %u1, i32 %u2) {
; CHECK-LABEL: define amdgpu_kernel void @prefer_uniform_grouping_umin(
; CHECK-SAME: i32 [[U1:%.*]], i32 [[U2:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[D_U2:%.*]] = call i32 @llvm.umin.i32(i32 [[D]], i32 [[U2]])
; CHECK-NEXT:    [[U1_U2:%.*]] = call i32 @llvm.umin.i32(i32 [[U1]], i32 [[U2]])
; CHECK-NEXT:    call void @use(i32 [[D_U2]])
; CHECK-NEXT:    call void @use(i32 [[U1_U2]])
; CHECK-NEXT:    [[RESULT_NARY:%.*]] = call i32 @llvm.umin.i32(i32 [[U1_U2]], i32 [[D]])
; CHECK-NEXT:    call void @use(i32 [[RESULT_NARY]])
; CHECK-NEXT:    ret void
;
  %d = call i32 @llvm.amdgcn.workitem.id.x()

  %d_u2 = call i32 @llvm.umin.i32(i32 %d, i32 %u2)
  %u1_u2 = call i32 @llvm.umin.i32(i32 %u1, i32 %u2)

  call void @use(i32 %d_u2)
  call void @use(i32 %u1_u2)

  %tmp = call i32 @llvm.umin.i32(i32 %d, i32 %u1)
  %result = call i32 @llvm.umin.i32(i32 %tmp, i32 %u2)
  call void @use(i32 %result)

  ret void
}

; Test GEP: prefer uniform remainder in index calculation
; For GEP with index = LHS + RHS:
;   - If RHS is uniform, prefer LHS first (uniform RHS as remainder)
;   - If LHS is uniform, prefer RHS first (uniform LHS as remainder)
define amdgpu_kernel void @prefer_uniform_gep_remainder(ptr %base, i64 %u_offset) {
; CHECK-LABEL: define amdgpu_kernel void @prefer_uniform_gep_remainder(
; CHECK-SAME: ptr [[BASE:%.*]], i64 [[U_OFFSET:%.*]]) {
; CHECK-NEXT:    [[D:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[D_EXT:%.*]] = zext i32 [[D]] to i64
; CHECK-NEXT:    [[GEP_D:%.*]] = getelementptr i32, ptr [[BASE]], i64 [[D_EXT]]
; CHECK-NEXT:    call void @use_ptr(ptr [[GEP_D]])
; CHECK-NEXT:    [[GEP_RESULT:%.*]] = getelementptr i32, ptr [[GEP_D]], i64 [[U_OFFSET]]
; CHECK-NEXT:    call void @use_ptr(ptr [[GEP_RESULT]])
; CHECK-NEXT:    ret void
;
  %d = call i32 @llvm.amdgcn.workitem.id.x()
  %d_ext = zext i32 %d to i64

  ; Create dominating GEP with divergent index
  %gep_d = getelementptr i32, ptr %base, i64 %d_ext
  call void @use_ptr(ptr %gep_d)

  ; GEP with index = d + u_offset
  ; Should prefer finding dominating GEP with d, leaving uniform u_offset as remainder
  %idx = add i64 %d_ext, %u_offset
  %gep_result = getelementptr i32, ptr %base, i64 %idx
  call void @use_ptr(ptr %gep_result)

  ret void
}

declare i32 @llvm.smax.i32(i32, i32)
declare i32 @llvm.smin.i32(i32, i32)
declare i32 @llvm.umax.i32(i32, i32)
declare i32 @llvm.umin.i32(i32, i32)
declare void @use_ptr(ptr)
